### ISSUE TITLE
Exception in thread "main" Syntax error compiling . at (clj_arangodb/arangodb/core.clj:29:5)

### ISSUE THREAD

**Issue by hamoser** [beoliver/clj-arangodb#23]
Hi Benjamin,

I was able to install with lein deps and [com.arangodb/arangodb-java-driver "6.17.0"] and [clj-arangodb "1.0.2"] in the project.clj file without issues, but when trying to start the server get the below stacktrace. 
A Google search pointed towards version conflicts as a possible reason for the HttpRequestRetryHandler error, so I deleted the apache dir in .m2 to let lein reinstall it, but the result is still the same.
Would you have an idea how to fix this?

Thanks,
Hans

lein ring server-headless
[main] INFO org.eclipse.jetty.util.log - Logging initialized @868ms
Exception in thread "main" Syntax error compiling . at (clj_arangodb/arangodb/core.clj:29:5).
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7114)
	at clojure.lang.Compiler.analyze(Compiler.java:6789)
...
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.NoClassDefFoundError: org/apache/http/client/HttpRequestRetryHandler
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3434)
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3459)
	at java.base/java.lang.Class.getMethods(Class.java:2051)
	at clojure.lang.Reflector.getMethods(Reflector.java:498)
	at clojure.lang.Compiler$InstanceMethodExpr.<init>(Compiler.java:1488)
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1024)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:7106)
	... 152 more
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.HttpRequestRetryHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 160 more
Subprocess failed (exit code: 1)

**Comment by beoliver** [comment]
Hi! The dependencies for the current version of this project look like 
```
[org.clojure/clojure "1.10.1"]
[com.arangodb/arangodb-java-driver "6.7.4"]
[org.slf4j/slf4j-simple "1.7.30"]
[cheshire "5.10.0"]
``` 
From what I can tell the [6.17.0 release](https://github.com/arangodb/arangodb-java-driver/tree/0bc7227704935b2f0da23862904b7c8823eaae62) of `com.arangodb/arangodb-java-driver` includes an optional dependency on `org.apache.httpcomponents/httpclient` which I believe is the source of `org.apache.http.client.HttpRequestRetryHandler`. If you search in the [pom.xml](https://github.com/arangodb/arangodb-java-driver/blob/0bc7227704935b2f0da23862904b7c8823eaae62/pom.xml) file you will see.
```
<dependency>
  <groupId>org.apache.httpcomponents</groupId>
  <artifactId>httpclient</artifactId>
  <optional>true</optional>
</dependency>
...
<dependency>
  <groupId>org.apache.httpcomponents</groupId>
  <artifactId>httpclient</artifactId>
  <version>4.5.13</version>
</dependency>
```


So I you might be able to just add the following to your deps.
```
[org.apache.httpcomponents/httpclient "4.5.13"]
```
However, you may have other issues with the client you would be using an _untested_ `arangodb-java-driver` version.
